branch-defaults:
  master:
    environment: prisoner-accounts-proto
deploy:
  artifact: Dockerrun.aws.json
  profile: eb-cli
environment-defaults:
  prisoner-accounts-proto:
    branch: null
    repository: null
global:
  application_name: prisoner-accounts-proto
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Multi-container Docker
    running on 64bit Amazon Linux/2.7.5
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
