defaults: &defaults
  working_directory: ~/app

version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run:
          name: Generate Build version
          command: |
            echo "export BUILD_VERSION=$(date +%Y%m%d%H%M)-$CIRCLE_BUILD_NUM" >> $BASH_ENV
      - checkout
      - run:
          name: Build Artifacts
          command: ./gradlew build
      - deploy:
          name: Install elastic beanstalk CLI
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/installElasticbeanstalk.sh
            fi
      - deploy:
          name: Deploy to Elastic Beanstalk Staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/deployElasticbeanstalk.sh $BUILD_VERSION
            fi
