version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run:
          name: Generate Build version
          command: |
            echo "export BUILD_VERSION=$(date +%Y%m%d%H%M)-$CIRCLE_BUILD_NUM" >> $BASH_ENV

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test

      - store_test_results:
          path: build/test-results

      - store_artifacts:
          path: build/reports/tests

      # Assemble
      - run: gradle assemble

      - store_artifacts:
          path: build/libs

      - setup_remote_docker

      - deploy:
          name: Push Service to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/publishServiceDockerImage.sh prisoner-accounts "${BUILD_VERSION}" "${CIRCLE_BUILD_NUM}" "${CIRCLE_BUILD_URL}" "${CIRCLE_SHA1}" "${DOCKER_EMAIL}" "${DOCKER_USERNAME}" "${DOCKER_PASSWORD}"
            fi

      - deploy:
          name: Push Web to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/publishWebDockerImage.sh prisoner-accounts "${BUILD_VERSION}" "${CIRCLE_BUILD_NUM}" "${CIRCLE_BUILD_URL}" "${CIRCLE_SHA1}" "${DOCKER_EMAIL}" "${DOCKER_USERNAME}" "${DOCKER_PASSWORD}"
            fi

      - deploy:
          name: Install elastic beanstalk CLI
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/installElasticbeanstalk.sh
            fi

#      - deploy:
#          name: Deploy to Elastic Beanstalk Staging
#          command: |
#            if [ "${CIRCLE_BRANCH}" == "master" ]; then
#              ./scripts/deployElasticbeanstalk.sh "${BUILD_VERSION}"
#            fi
